// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwJMT1mwWSeHo2m2KMmoBvuL4PjSdEFxg',
    appId: '1:834434973012:web:23a402296e002c6c3c9cc1',
    messagingSenderId: '834434973012',
    projectId: 'flutterfirebasebasics-76855',
    authDomain: 'flutterfirebasebasics-76855.firebaseapp.com',
    storageBucket: 'flutterfirebasebasics-76855.appspot.com',
    measurementId: 'G-L09VZC4Y6M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHSSCnEFMzVzeHJov4OWaYxRNMDzAWVCc',
    appId: '1:834434973012:android:b5c4f86c7d398ad73c9cc1',
    messagingSenderId: '834434973012',
    projectId: 'flutterfirebasebasics-76855',
    storageBucket: 'flutterfirebasebasics-76855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxDl_6vFcM2FfBFecejyg5jNn6oNT-Akg',
    appId: '1:834434973012:ios:b618b2d23d0b93163c9cc1',
    messagingSenderId: '834434973012',
    projectId: 'flutterfirebasebasics-76855',
    storageBucket: 'flutterfirebasebasics-76855.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxDl_6vFcM2FfBFecejyg5jNn6oNT-Akg',
    appId: '1:834434973012:ios:b618b2d23d0b93163c9cc1',
    messagingSenderId: '834434973012',
    projectId: 'flutterfirebasebasics-76855',
    storageBucket: 'flutterfirebasebasics-76855.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwJMT1mwWSeHo2m2KMmoBvuL4PjSdEFxg',
    appId: '1:834434973012:web:f285c445087b285b3c9cc1',
    messagingSenderId: '834434973012',
    projectId: 'flutterfirebasebasics-76855',
    authDomain: 'flutterfirebasebasics-76855.firebaseapp.com',
    storageBucket: 'flutterfirebasebasics-76855.appspot.com',
    measurementId: 'G-160LTXX2D1',
  );
}
